# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy the Nginx configuration file from the host to the container
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY uwsgi_params /etc/nginx/uwsgi_params

RUN chown -R nginx:nginx /var/log /etc/nginx

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]