# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy the Nginx configuration file from the host to the container
COPY default.conf /etc/nginx/conf.d/default.conf
COPY uwsgi_params /etc/nginx/uwsgi_params

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]